/**
 * Single place where R2 URLs are constructed.
 * All media on the site goes through these builders — keeps URL format
 * consistent so browser cache hits across components (preload, thumbnails,
 * viewer all share the same `-lo.jpg` URL etc.).
 */

import type { MediaFile } from "./manifest";

const BASE = import.meta.env.PUBLIC_R2_BASE ?? "";

if (!BASE && typeof window !== "undefined") {
    console.warn("PUBLIC_R2_BASE is not set — media URLs will be broken.");
}

const join = (id: string, suffix: string) => `${BASE}/${id}${suffix}`;

/** Tiny blurry placeholder (~3-5 KB). Same URL used as video poster. */
export function lowResUrl(file: MediaFile): string {
    return join(file.id, "-lo.jpg");
}

/** Mid-resolution working quality (h=800). */
export function midResUrl(file: MediaFile): string {
    return join(file.id, "-mid.jpg");
}

/** Full quality hi-res image. */
export function hiResUrl(file: MediaFile): string {
    return join(file.id, ".jpg");
}

/** Source MP4 for video files (viewer-grade). */
export function videoSrcUrl(file: MediaFile): string {
    return join(file.id, ".mp4");
}

/** Tiny low-bitrate clip for index thumbnails (~200-500 KB). */
export function thumbVideoUrl(file: MediaFile): string {
    return join(file.id, "-mid.mp4");
}

/** Video poster — same low-res JPG generated by ffmpeg during migration. */
export function posterUrl(file: MediaFile): string {
    return join(file.id, "-lo.jpg");
}

/**
 * For index thumbnails we render `-lo` first, then upgrade on row hover.
 * Images → `-mid.jpg`. Videos use a `<video>` element with `-mid.mp4`,
 * see thumbVideoUrl() — this helper is for the static-image fallback only.
 */
export function thumbHiUrl(file: MediaFile): string {
    if (file.type === "video") return join(file.id, "-lo.jpg");
    return join(file.id, "-mid.jpg");
}
